server:
  type: default
  rootPath: /foxtrot/
  adminContextPath: /admin
  applicationConnectors:
    - port: 18000
      type: http
  adminConnectors:
    - port: 18001
      type: http

elasticsearch:
  hosts:
  - localhost
  cluster: foxtrot

hbase:
  secure : false
  tableName: foxtrot

cluster:
  name: foxtrot
  disableMulticast: true
  members: ["localhost:5701", "localhost:5702"]

logging:
  level: INFO

deletionconfig:
  active: true
  interval: 86400
  initialdelay: 60
